language: python
python: 3.4
install:
    - pip install -e .[dev]
    - pip install coverage
    - pip install coveralls
script: coverage run --source=gro_state --omit=*test*,*migrations* manage.py -d test gro_state.farms
after_success: coveralls
