language: python
python: 3.4
install:
    - pip install .
    - pip install coverage
    - pip install coveralls
    - oa_data_manager_configure -d
script: coverage run --source=. --omit=env/*,*test*,*migrations* setup.py test
after_success: coveralls
